export enum AdminActionTypes {
  API_RESPONSE_SUCCESS = "@@admin/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR = "@@admin/API_RESPONSE_ERROR",
  CREATE_CRED_ADMIN_USER = "@@admin/CREATE_CRED_ADMIN_USER",
  EDIT_CRED_ADMIN_USER = "@@admin/EDIT_CRED_ADMIN_USER",
  GET_CRED_ADMIN_USERS = "@@admin/GET_CRED_ADMIN_USERS",
  GET_CRED_ADMIN_USERS_BY_ID = "@@admin/GET_CRED_ADMIN_USERS_BY_ID",
  DELETE_CRED_ADMIN_USERS = "@@admin/DELETE_CRED_ADMIN_USERS",
}
