export enum AdminActionTypes {
  API_RESPONSE_SUCCESS = "@@admin/API_RESPONSE_SUCCESS",
  API_RESPONSE_ERROR = "@@admin/API_RESPONSE_ERROR",

  CREATE_ADMIN_USER = "@@admin/CREATE_ADMIN_USER",
  EDIT_ADMIN_USER = "@@admin/EDIT_ADMIN_USER",
  GET_ADMIN_USERS = "@@admin/GET_ADMIN_USERS",
  GET_ADMIN_USERS_BY_ID = "@@admin/GET_ADMIN_USERS_BY_ID",
  DELETE_ADMIN_USERS = "@@admin/DELETE_ADMIN_USERS",
}
